name: Lint

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python packages
        run: |
          python -m pip install requirements-lint.txt
      - name: Lint
        run: bash scripts/lint.sh
