name: Ruff

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1  # lint
      - uses: chartboost/ruff-action@v1  # format check
        with:
          args: 'format --check'
