name: Lint

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1  # lint
      - uses: chartboost/ruff-action@v1  # format check
        with:
          args: 'format --check'
